// Products Data - Dữ liệu sản phẩm
const productsData = [
  { "id": 3, "title": "Classic Heather Gray Hoodie", "slug": "classic-heather-gray-hoodie", "price": 69, "description": "Stay cozy and stylish with our Classic Heather Gray Hoodie.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/cHddUCu.jpeg"] },
  { "id": 6, "title": "Classic Comfort Fit Joggers", "slug": "classic-comfort-fit-joggers", "price": 25, "description": "Discover the perfect blend of style and comfort.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/ZKGofuB.jpeg"] },
  { "id": 7, "title": "Classic Comfort Drawstring Joggers", "slug": "classic-comfort-drawstring-joggers", "price": 79, "description": "Experience the perfect blend of comfort and style.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/mp3rUty.jpeg"] },
  { "id": 8, "title": "Classic Red Jogger Sweatpants", "slug": "classic-red-jogger-sweatpants", "price": 98, "description": "Experience ultimate comfort with our red jogger sweatpants.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/9LFjwpI.jpeg"] },
  { "id": 9, "title": "Classic Navy Blue Baseball Cap", "slug": "classic-navy-blue-baseball-cap", "price": 61, "description": "Step out in style with this sleek navy blue baseball cap.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/R3iobJA.jpeg"] },
  { "id": 10, "title": "Classic Blue Baseball Cap", "slug": "classic-blue-baseball-cap", "price": 86, "description": "Top off your casual look with our Classic Blue Baseball Cap.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/wXuQ7bm.jpeg"] },
  { "id": 11, "title": "Classic Red Baseball Cap", "slug": "classic-red-baseball-cap", "price": 35, "description": "Elevate your casual wardrobe with this timeless red baseball cap.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/cBuLvBi.jpeg"] },
  { "id": 12, "title": "Classic Black Baseball Cap", "slug": "classic-black-baseball-cap", "price": 58, "description": "Elevate your casual wear with this timeless black baseball cap.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/KeqG6r4.jpeg"] },
  { "id": 13, "title": "Classic Olive Chino Shorts", "slug": "classic-olive-chino-shorts", "price": 84, "description": "Elevate your casual wardrobe with these classic olive chino shorts.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/UsFIvYs.jpeg"] },
  { "id": 14, "title": "Classic High-Waisted Athletic Shorts", "slug": "classic-high-waisted-athletic-shorts", "price": 43, "description": "Stay comfortable and stylish with our Classic High-Waisted Athletic Shorts.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/eGOUveI.jpeg"] },
  { "id": 15, "title": "Classic White Crew Neck T-Shirt", "slug": "classic-white-crew-neck-t-shirt", "price": 39, "description": "Elevate your basics with this versatile white crew neck tee.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/axsyGpD.jpeg"] },
  { "id": 16, "title": "Classic White Tee - Timeless Style and Comfort", "slug": "classic-white-tee-timeless-style-and-comfort", "price": 73, "description": "Elevate your everyday wardrobe with our Classic White Tee.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/Y54Bt8J.jpeg"] },
  { "id": 17, "title": "Classic Black T-Shirt", "slug": "classic-black-t-shirt", "price": 35, "description": "Elevate your everyday style with our Classic Black T-Shirt.", "category": { "id": 1, "name": "Clothes", "slug": "clothes" }, "images": ["https://i.imgur.com/9DqEOV5.jpeg"] },
  { "id": 18, "title": "Sleek White & Orange Wireless Gaming Controller", "slug": "sleek-white-orange-wireless-gaming-controller", "price": 69, "description": "Elevate your gaming experience.", "category": { "id": 2, "name": "Electronics", "slug": "electronics" }, "images": ["https://i.imgur.com/ZANVnHE.jpeg"] },
  { "id": 19, "title": "Sleek Wireless Headphone & Inked Earbud Set", "slug": "sleek-wireless-headphone-inked-earbud-set", "price": 44, "description": "Experience the fusion of style and sound.", "category": { "id": 2, "name": "Electronics", "slug": "electronics" }, "images": ["https://i.imgur.com/yVeIeDa.jpeg"] },
  { "id": 20, "title": "Sleek Comfort-Fit Over-Ear Headphones", "slug": "sleek-comfort-fit-over-ear-headphones", "price": 28, "description": "Experience superior sound quality.", "category": { "id": 2, "name": "Electronics", "slug": "electronics" }, "images": ["https://i.imgur.com/SolkFEB.jpeg"] }
];

module.exports = productsData;